---
namespace: ansible
name: ah
version: 1.0.0
readme: README.md
authors:
  - Sean Sullivan (github.com/sean-m-sullivan)
  - Tom Page (github.com/Tompage1994)
  - David Danielsson (github.com/djdanielsson)
  - Abhijeet Kasurde (github.com/Akasurde)
description: Ansible content that interacts with the Ansible Automation Hub
license_file: LICENSE
tags:
  - cloud
  - infrastructure
  - galaxy
  - ansible
  - galaxy
  - automation
repository: https://github.com/ansible-collections/ansible_hub
homepage: https://github.com/ansible-collections/ansible_hub
issues: https://github.com/ansible-collections/ansible_hub/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - tools
  - setup.cfg
  - galaxy.yml.j2
  - template_galaxy.yml
  - '*.tar.gz'
  - test
  - galaxy_ng